"""Model components for CoSER-DiC."""

from .conditioning_adapter import CoSERConditioningAdapter, ConditioningAdapterConfig
from .coserdic import CoSERDiC, CoSEROutput
from .diffusion_decoder import CoSERDiffusionDecoder, DiffusionDecoderConfig
from .decoder_refiner import DecoderSideRefiner, DecoderSideRefinerConfig
from .gencodec_backbone import (
    CoDLiteOneStepBackbone,
    CoDLiteOneStepBackboneConfig,
    CoSERToCoDLiteConditionAdapter,
    CoSERToCoDLiteConditionAdapterConfig,
    CoSERToCoDLiteConditionGate,
    CoSERToCoDLiteConditionGateConfig,
    CoSERToCoDLiteAlphaGate,
    CoSERToCoDLiteAlphaGateConfig,
    CoSERToCoDLiteConditionPyramidAdapter,
    CoSERToCoDLiteConditionPyramidAdapterConfig,
    LoRAConv2d,
    LoRALinear,
    apply_lora_adapters_by_name,
    apply_lora_adapters_from_config,
    condition_residual_rms_guard,
    lora_parameter_names,
    load_named_parameter_state,
    named_parameter_state,
    set_trainable_parameters_by_name,
)
from .postprocess import DECODER_POSTPROCESS_MODES, apply_decoder_postprocess, gaussian_blur_3x3
from .residual_detail import (
    ResidualDetailAutoEncoder,
    ResidualDetailConfig,
    ResidualDetailDecoder,
    ResidualDetailEncoder,
    UniformScalarQuantizer,
)
from .semantic_vq import (
    DifferentiableVQ,
    SemanticAuxiliaryDecoder,
    SemanticEncoder,
    SemanticVQAutoEncoder,
    SemanticVQConfig,
)
from .token_prior import (
    CausalTokenPrior,
    CausalTokenPriorConfig,
    decoder_prefix_topk_indices,
    decoder_schedule_topk_indices,
    shifted_causal_inputs,
    topk_from_prefix,
)

__all__ = [
    "CoSERConditioningAdapter",
    "CoSERDiC",
    "CoSERDiffusionDecoder",
    "CoDLiteOneStepBackbone",
    "CoDLiteOneStepBackboneConfig",
    "CoSEROutput",
    "ConditioningAdapterConfig",
    "CoSERToCoDLiteConditionAdapter",
    "CoSERToCoDLiteConditionAdapterConfig",
    "CoSERToCoDLiteConditionGate",
    "CoSERToCoDLiteConditionGateConfig",
    "CoSERToCoDLiteAlphaGate",
    "CoSERToCoDLiteAlphaGateConfig",
    "CoSERToCoDLiteConditionPyramidAdapter",
    "CoSERToCoDLiteConditionPyramidAdapterConfig",
    "LoRAConv2d",
    "LoRALinear",
    "apply_lora_adapters_by_name",
    "apply_lora_adapters_from_config",
    "condition_residual_rms_guard",
    "lora_parameter_names",
    "load_named_parameter_state",
    "named_parameter_state",
    "set_trainable_parameters_by_name",
    "CausalTokenPrior",
    "CausalTokenPriorConfig",
    "decoder_prefix_topk_indices",
    "decoder_schedule_topk_indices",
    "DECODER_POSTPROCESS_MODES",
    "DifferentiableVQ",
    "DiffusionDecoderConfig",
    "DecoderSideRefiner",
    "DecoderSideRefinerConfig",
    "apply_decoder_postprocess",
    "gaussian_blur_3x3",
    "ResidualDetailAutoEncoder",
    "ResidualDetailConfig",
    "ResidualDetailDecoder",
    "ResidualDetailEncoder",
    "SemanticAuxiliaryDecoder",
    "SemanticEncoder",
    "SemanticVQAutoEncoder",
    "SemanticVQConfig",
    "shifted_causal_inputs",
    "topk_from_prefix",
    "UniformScalarQuantizer",
]
